/**
 * Single source of truth for every word on the site.
 * Edit here, never in the components.
 */

export const site = {
  name: "Anish Shejawale",
  role: "Backend Developer",
  location: "Bengaluru, India",
  domain: "anishdevlops.xyz",
  url: "https://anishdevlops.xyz",
  email: "anishwork69@gmail.com",
  github: "https://github.com/Anish358",
  linkedin: "https://www.linkedin.com/in/anish358",
  resume: "/Anish-Shejawale-Backend-Developer.pdf",
  tagline: "I build APIs and data models — and run what I ship.",
  intro:
    "Two years building the systems behind data-heavy products in Node.js and Django. Alongside work I designed, built and operate PropVexis, a live multi-tenant SaaS, entirely on my own — including the AWS infrastructure, CI/CD and monitoring underneath it.",
  currently: "Backend Developer at Kamakhya Analytics",
  availability: "Open to backend and platform roles",
} as const;

/**
 * Runtime copy for the assistant. The panel's own labels live in
 * `editorial.ask`; what's left here is the text the request path needs.
 *
 * The last suggestion is deliberate: an engineer clicks "what's he not
 * experienced in" first, and the honest answer is the most persuasive thing on
 * the page.
 */
export const assistant = {
  /**
   * This has to stay true, and it got longer when the assistant moved to
   * Gemini's free tier: free-tier input is used by Google to improve their
   * models. A visitor typing into this box is handing text to a third party,
   * and not saying so on a site whose whole argument is that it doesn't
   * overstate things would be indefensible.
   */
  disclaimer:
    "Answers are generated by Google's Gemini from a fixed set of facts, so check anything that matters — and note Google may use what you type to improve their models. Questions are logged here too, anonymously: no IP, no answers, no way to tie them to you. The conversation itself isn't stored and goes when you close the tab.",
  suggestions: [
    "What has he actually built?",
    "Is he a fit for a backend role?",
    "What's his experience with AWS?",
    "What's he not experienced in?",
  ],
  send: "Send",
  /** Last-resort copy when the network fails before the server can answer. */
  offline: "Couldn't reach the assistant. Please try again, or use the contact form below.",
} as const;

/** The real GitHub Actions stages behind app.propvexis.com. */
export const pipeline = [
  { stage: "test", detail: "node:test suite" },
  { stage: "build", detail: "frontend bundle" },
  { stage: "ship", detail: "rsync to EC2" },
  { stage: "migrate", detail: "schema forward" },
  { stage: "release", detail: "pm2 restart" },
] as const;

/**
 * PropVexis data path, drawn as a diagram in <Architecture />.
 * Coordinates live in the component; this is the copy.
 */
export const architecture = {
  caption:
    "A closed trade leaves MetaTrader 5 and is on the trader's screen in under a second. Every hop is idempotent, so nothing double-counts on retry.",
  nodes: [
    { id: "agent", title: "MT5 Agent", sub: "MQL5" },
    { id: "ingest", title: "Ingest API", sub: "Fastify · idempotent" },
    { id: "db", title: "PostgreSQL", sub: "CTEs · composite idx" },
    { id: "cache", title: "Stats Cache", sub: "in-process · LRU + TTL" },
    { id: "rules", title: "Rule Engine", sub: "drawdown · targets" },
    { id: "client", title: "Browser", sub: "Socket.IO" },
  ],
} as const;

export type Project = {
  slug: string;
  name: string;
  badge: string;
  /** Internal route to a longer write-up, if one exists. */
  caseStudy?: string;
  oneLiner: string;
  problem: string;
  /**
   * `body` is the published prose. `detail` is for facts the prose leaves out
   * — the assistant reads both, the page renders only `body`.
   */
  features: { title: string; body: string; detail?: string }[];
  infra?: string;
  stack: string[];
  /** The four-or-so technologies printed under a work row. */
  stackLine: string;
  /** Three stages drawn as a connected run in the hover-revealed detail. */
  flow: [string, string, string];
  /** One line of hard numbers under that run. */
  stat: string;
  links: { label: string; href: string }[];
};

export const projects: Project[] = [
  {
    slug: "propvexis",
    name: "PropVexis",
    badge: "Flagship · Live in production",
    caseStudy: "/propvexis",
    oneLiner:
      "A multi-tenant SaaS trading journal for prop-firm traders. Designed, built and operated solo.",
    problem:
      "Traders on funded prop accounts get one shot at a strict rule set — breach the daily or maximum drawdown and the account is gone. Most of them track it in spreadsheets that tell them what happened yesterday, not that they are 0.4% away from losing the account right now.",
    features: [
      {
        title: "Real-time ingestion end to end",
        body: "An MQL5 Expert Advisor inside the trader's MetaTrader 5 terminal posts closed trades to a Fastify endpoint over HTTPS with a per-account token. The write is an upsert keyed on (account, MT5 ticket), so an EA that retries or reconnects mid-batch cannot double-count a fill. The trade lands in PostgreSQL and Socket.IO pushes it into that user's room — there is no polling anywhere in the path, so an open dashboard moves as positions close.",
        detail:
          "The Expert Advisor is the free ingestion path. A connector layer behind a sync queue feeds the same seam from MT5 credentials, cTrader OAuth and TradeLocker, with broker secrets sealed under AES-256-GCM whose additional authenticated data is the account id — so a ciphertext lifted from one account's row cannot be replayed into another's.",
      },
      {
        title: "A configurable rule engine",
        body: "Every prop firm writes its rules differently: daily drawdown measured from balance or from equity, maximum drawdown static or trailing, profit targets and minimum trading days. Each firm's rule set is stored as data and evaluated against the account after every trade, so the engine reports distance to breach rather than a verdict after the fact.",
        detail:
          "Alerts carry a dedup key, so a proximity warning fires once rather than on every write. Breach is evaluated first and is terminal: an account that crosses its drawdown and its profit target on the same trade is breached, not passed.",
      },
      {
        title: "Analytics moved into the database",
        body: "Equity curves, strike rate, expectancy, profit factor, R-distribution, MFE efficiency and breakdowns by setup, session, instrument and period are computed in PostgreSQL — one CTE query per request over composite indexes, with win/loss streaks done as gap-and-islands. SQL does only COUNT, SUM and GROUP BY; every derived number stays in JavaScript, so a mistake in the SQL surfaces as a count mismatch rather than a quietly different formula.",
        detail:
          "What made the rewrite safe was keeping the original JavaScript implementation as the test oracle — the suite asserts the SQL path returns the same numbers for the same trades, or the build fails. Results are cached per user and per filter set and dropped by the write that changes them, bounded by LRU plus a TTL backstop because the box has 1 GB of RAM. Rule adherence stays in JavaScript: it evaluates JSONB predicates per trade, which SQL cannot express, and is fetched only for strategies that actually define rules.",
      },
      {
        title: "Multi-tenancy and billing",
        body: "Every query is scoped by user id, with Google OAuth and email sessions issued as JWTs in httpOnly Secure cookies. Free, Pro and Premium tiers gate account limits and history depth on Razorpay recurring subscriptions, whose webhooks are signature-verified with a timing-safe HMAC over the exact raw request bytes.",
        detail:
          "Passwords are hashed with scrypt from node:crypto rather than bcrypt or argon2, so nothing needs a native build step on a t3.micro that deploys by rsync. Because sessions are stateless JWTs, a password reset would otherwise leave an attacker's existing token working — so every token carries the user's session epoch, a reset bumps it, and that evicts live sessions including open WebSockets.",
      },
    ],
    infra:
      "GitHub Actions deploys on merge to main — test-gated, then build, rsync to EC2, auto-migrate, pm2 reload — across three isolated environments on a single t3.micro in ap-south-1. Caddy terminates TLS automatically and reverse-proxies the API and the WebSocket. Secrets load from SSM Parameter Store through the instance IAM role and fail closed if SSM is unreachable, so no static AWS keys and no secret values sit on disk. Nightly pg_dump to S3 under a least-privilege instance role with 90-day lifecycle expiry, restores verified with pg_restore. Sentry on both ends, Prometheus and Grafana for RED metrics and connection-pool saturation, and a Route53 health check into CloudWatch and SNS that catches an outage in about 90 seconds.",
    /*
     * Redis is deliberately absent. The integration is written and tested
     * (shared socket adapter, cross-worker cache invalidation) but it is not
     * provisioned in production, which ships one worker per environment — so
     * listing it here would claim a running dependency that isn't running.
     */
    stack: [
      "Node.js",
      "Fastify",
      "PostgreSQL",
      "Socket.IO",
      "React",
      "MQL5",
      "AWS",
      "Caddy",
      "pm2",
      "Terraform",
      "Docker",
      "GitHub Actions",
      "Prometheus",
      "Sentry",
    ],
    stackLine: "Node.js · Fastify · PostgreSQL · Socket.IO · AWS",
    flow: ["INGEST", "EVALUATE", "STREAM"],
    stat: "1,711 tests · 31 migrations · 3 envs on one t3.micro",
    links: [
      { label: "Live site", href: "https://app.propvexis.com" },
      { label: "GitHub", href: "https://github.com/Anish358/propvexis" },
    ],
  },
  {
    slug: "luxora",
    name: "Luxora",
    badge: "E-commerce platform",
    caseStudy: "/luxora",
    oneLiner:
      "A full MERN storefront built end to end — catalogue, cart, cash-on-delivery checkout, and a separate operator console.",
    problem:
      "Built to work through the parts of commerce that are actually fiddly rather than the parts that demo well: keeping a catalogue coherent across categories and sizes, holding a cart that survives a login, and giving an operator somewhere to move an order through its stages.",
    features: [
      {
        title: "Catalogue and storefront",
        body: "Nine storefront pages over an Express and MongoDB API: a catalogue spanning Men, Women and Kids, each with topwear, bottomwear and winterwear, searched and filtered on the client, with per-size selection on the product page. Product images upload through Multer and are served from Cloudinary rather than off the app box.",
      },
      {
        title: "A cart that survives the session",
        body: "The cart lives on the user document in MongoDB rather than in browser state, so it follows a login across devices. Checkout writes an order with its items, amount and address and empties the cart in the same flow, and every customer gets their own order history.",
      },
      {
        title: "Operator console",
        body: "A second React app against the same API, gated by its own admin middleware: add a product with several images at once, list and remove stock, and walk an order through its fulfilment stages. Customer and admin routes are separated at the middleware layer, so an ordinary user token cannot reach an admin endpoint.",
        detail:
          "Auth is bcrypt with a generated salt plus JWTs, and email format is validated server-side before a user row is written. The admin surface is a separate deployable, not a route inside the storefront.",
      },
    ],
    stack: [
      "React",
      "Vite",
      "React Router",
      "Tailwind CSS",
      "Express",
      "MongoDB",
      "Mongoose",
      "JWT",
      "bcrypt",
      "Cloudinary",
      "Multer",
      "Render",
    ],
    stackLine: "React · Express · MongoDB · Cloudinary · Render",
    flow: ["CATALOGUE", "CART", "FULFILMENT"],
    stat: "3 apps · 52-product seed · admin-gated API",
    links: [
      { label: "Live site", href: "https://luxora-mu.vercel.app/" },
      { label: "GitHub", href: "https://github.com/Anish358/luxora" },
    ],
  },
];

/** Long-form write-up at /propvexis. The trade-offs are the point. */
/**
 * Long-form write-up at /propvexis. The trade-offs are the point.
 *
 * `body` is the published prose; `detail` carries the reasoning the card-sized
 * copy has to leave out, which the assistant still answers from.
 */
export const caseStudy = {
  decisions: [
    {
      kicker: "DELIVERY",
      title: "Idempotent ingest, not at-most-once delivery",
      body: "The agent retries whenever the network drops, which means the same trade can arrive several times. Deduplicating on (account, MT5 ticket) at write time makes replays harmless, at the cost of a uniqueness constraint the ingest path has to honour and a slightly heavier write.",
      detail:
        "The agent runs on a trader's home PC over a connection I don't control, so retries and duplicate batches aren't edge cases — they're the normal operating condition. Deduplicating at write time lets the agent retry blindly and stay dumb. The alternative, tracking acknowledgement state on the client, puts correctness in the least reliable part of the system.",
    },
    {
      kicker: "RULES",
      title: "Rule sets as data, not code",
      body: "Encoding each firm's rules in application logic would have been faster to write and impossible to maintain past the third firm. Storing them as data means onboarding a firm is a row rather than a release, and it means the engine has to validate configurations it has never seen.",
      detail:
        "Every prop firm has a different drawdown basis, reset time and minimum trading days. One evaluator covers all of them. The cost is a more abstract engine and validation I have to write by hand instead of getting it from the type system.",
    },
    {
      kicker: "AGGREGATION",
      title: "Aggregation in PostgreSQL, not in Node",
      body: "Pulling rows into the application and reducing them there is easier to read and gets slow as history grows. Keeping the work in SQL trades that readability for stable latency, and puts the burden on indexes and query plans that have to be maintained deliberately.",
      detail:
        "What made the rewrite safe was that the existing tests asserting on the JavaScript aggregation became the oracle for the SQL version — same inputs, same numbers, or the build fails.",
    },
    {
      kicker: "CACHING",
      title: "Invalidation over short TTLs",
      body: "A short expiry would have been simpler, but a trader cannot be shown a drawdown figure that is thirty seconds stale. Cached reads are invalidated by the write that changes them, which means every write path has to know what it affects.",
      detail:
        "Invalidation fans out over Redis pub/sub when REDIS_URL is set, which is what makes more than one worker possible — it ships one worker per environment today, so that fan-out is written and tested rather than in service. The invariant is that local invalidation never depends on the transport: if the publish fails, the worker that handled the write still drops its own entries, because showing the writing user their own stale dashboard is worse than the cross-worker staleness this fixes.",
    },
    {
      kicker: "SESSIONS",
      title: "httpOnly cookies over localStorage tokens",
      body: "Tokens in localStorage are convenient for the client and readable by any script that gets onto the page. Cookies the browser will not hand to JavaScript remove that class of theft, and in exchange require CSRF protection and explicit cross-origin handling.",
      detail:
        "CSRF handling and a same-site policy are a smaller and much better-understood problem than token theft.",
    },
    {
      kicker: "TENANCY",
      title: "Row-level tenant scoping over schema-per-tenant",
      body: "A schema per tenant isolates data firmly and turns every migration into an operation across N schemas. Scoping by tenant id on the row keeps migrations single and moves the burden onto query discipline: no read path is allowed to omit the scope.",
      detail:
        "The isolation risk is concentrated where I can test it directly, so there are tests that assert one tenant's queries can never return another's rows.",
    },
  ],
  /** `label` is what the page prints; `detail` is what the assistant reads. */
  next: [
    {
      label: "Move PostgreSQL off the application box",
      detail:
        "All three environments share one native PostgreSQL 16 instance on the same t3.micro as the API. That co-location is the system's single point of failure and the first thing I would fix; a managed instance also lifts the max_connections ceiling that currently caps how many workers can run.",
    },
    {
      label: "Provision Redis and run more than one worker",
      detail:
        "Both correctness blockers for pm2 cluster mode — a shared Socket.IO adapter and cross-worker cache invalidation — are already solved in code behind REDIS_URL. What remains is operational: provision Redis, upsize the instance (each worker is 90 to 150 MB RSS on a 1 GB box already running three environments), and lower PG_POOL_MAX, since total connections are workers times pool size against a max_connections of 100.",
    },
    {
      label: "Finish the connector layer and scale the sync fleet",
      detail:
        "MT5 credential sync, cTrader OAuth and TradeLocker connectors already feed one ingestion seam behind a queue. The next step is a horizontally scaled sync-worker fleet, so cloud sync stops sharing a process with the API.",
    },
  ],
} as const;

export const experience = [
  {
    company: "Varahe Analytics → Kamakhya Analytics",
    note: "subsidiary — continuous tenure",
    role: "Backend Developer",
    period: "May 2025 — Present",
    /** One-line framing of the role, for the editorial experience row. */
    summary:
      "Building and maintaining the backend APIs, data pipelines and internal dashboards the analytics teams run on, across Django, PostgreSQL and MongoDB.",
    /** The same work as `points`, cut to the three that carry a number. */
    highlights: [
      "Cut database load 40% with ORM and Redis caching",
      "Automated the data audit into a transcribe-and-validate pipeline",
      "Hardened auth across MongoDB and PostgreSQL systems",
    ],
    points: [
      "Built and optimised backend APIs in Django and SQL, using the ORM and Redis caching to cut database load by 40% and improve API response times.",
      "Automated the company's data-audit process end to end: a pipeline that transcribes surveyor audio recordings and validates them against the corresponding database records, replacing line-by-line manual review with exception-only review by auditors.",
      "Implemented secure authentication and authorisation flows across MongoDB and PostgreSQL systems, increasing reliability and reducing auth-related issues.",
      "Built full-stack features in React, Redux and Django, including the data-dense dashboards with charts and tables that internal teams rely on daily — a 35% improvement in how quickly they get to a number.",
      "Cut client-side load times by 30% through lazy loading, RTK Query caching and tighter state management.",
    ],
  },
  {
    company: "OpenStudyAI",
    role: "Full Stack Developer",
    period: "Dec 2024 — May 2025",
    summary:
      "Owned the platform's front-end architecture end to end and automated its AI content generation on AWS Bedrock.",
    highlights: [
      "Automated AI content generation on AWS Bedrock",
      "Designed the entire front-end architecture",
      "Improved scalability 30% by optimising Redux state",
    ],
    points: [
      "Automated AI content generation on AWS Bedrock, cutting manual workload and increasing output by 50%.",
      "Designed and developed the entire front-end architecture for the platform.",
      "Improved platform scalability by 30% by optimising Redux-based state management, resulting in faster load times.",
    ],
  },
] as const;

export const skills = [
  {
    group: "Backend",
    items: ["Node.js", "Fastify", "Express", "Django", "Python", "REST", "WebSockets"],
  },
  {
    group: "Databases",
    items: ["PostgreSQL", "MongoDB", "Redis", "MySQL", "SQL", "Query optimisation"],
  },
  {
    group: "Cloud & DevOps",
    items: [
      "AWS",
      "EC2",
      "S3",
      "IAM",
      "SSM",
      "Docker",
      "Kubernetes",
      "Terraform",
      "GitHub Actions",
      "CI/CD",
      "Linux",
    ],
  },
  {
    group: "AI & LLMs",
    items: ["Claude / OpenAI APIs", "Prompt & context engineering"],
  },
  {
    group: "Frontend",
    items: ["React", "Next.js", "TypeScript", "Redux", "Tailwind CSS"],
  },
  {
    group: "Observability",
    items: ["Prometheus", "Grafana", "Sentry"],
  },
] as const;

/**
 * Copy for the editorial homepage.
 *
 * The layout comes from editorial-design-system/; the words come from the
 * exports above wherever a real fact exists, so nothing on the page is a
 * mockup placeholder. Labels are stored pre-uppercased because the design
 * sets them in Space Mono with wide tracking, where `text-transform` and
 * hand-cased text kern differently.
 */
/** Resolved when the page is built, so a deploy carries the year forward. */
const year = new Date().getFullYear();

export const editorial = {
  brand: site.name.toUpperCase(),
  nav: [
    { label: "WORK", href: "#work" },
    { label: "EXPERIENCE", href: "#experience" },
    { label: "ABOUT", href: "#about" },
    { label: "CONTACT", href: "#contact" },
  ],
  askShortcut: "ASK",

  hero: {
    kicker: `PORTFOLIO / ${year}`,
    /** Set as two lines in the design; the break is deliberate, not a wrap. */
    title: ["ANISH", "SHEJAWALE"],
    role: "BACKEND DEVELOPER",
    locale: "IN / UTC+5:30",
    lede: site.tagline,
    aside: [
      { label: "STATUS", kind: "status", value: "AVAILABLE FOR OPPORTUNITIES" },
      {
        label: "FOCUS",
        kind: "list",
        items: ["Backend Systems", "Cloud Infrastructure", "Applied AI"],
      },
      { label: "LOCATION", kind: "value", value: site.location },
      {
        label: "CURRENTLY BUILDING",
        kind: "value",
        value: "PropVexis — a live multi-tenant SaaS trading journal",
      },
    ],
  },

  /**
   * FIG. 01 — the PropVexis write path, same six nodes as `architecture`
   * above, mapped onto the design's fixed 1200×150 geometry.
   */
  figure: {
    caption: "FIG. 01 — HOW A CLOSED TRADE REACHES THE TRADER'S SCREEN",
    mode: "WRITE PATH / IDEMPOTENT",
    source: "MT5 AGENT",
    api: "INGEST API",
    apiSub: "idempotent writes",
    upper: "POSTGRESQL",
    lower: "CACHE",
    lowerSub: "in-process · per user",
    /*
     * "RULES", not "RULE ENGINE" as on the case study. The design tuned this
     * node's geometry around a six-character label: the dashed feedback arc
     * leaves the node and passes just under the baseline. A longer label grows
     * out into the arc's path and gets struck through. The case-study diagram
     * has no arc overhead and spells it out in full.
     */
    worker: "RULES",
    workerSub: "drawdown · targets",
    sink: "BROWSER",
    sinkSub: "under 1s end to end",
    loop: "invalidate on write",
  },

  work: {
    label: "01 / SELECTED WORK",
    archive: "ARCHIVE",
    archiveLink: { label: "→ ALL PROJECTS", href: site.github },
    caseStudyCta: "→ VIEW CASE STUDY",
    projectCta: "→ VIEW PROJECT",
  },

  experience: {
    label: "02 / EXPERIENCE",
    impactLabel: "SELECTED IMPACT",
    footer: "FULL HISTORY",
    footerLink: { label: "→ RESUME", href: site.resume },
  },

  about: {
    label: "03 / ABOUT",
    statement:
      "I'm a software engineer interested in understanding what happens underneath the abstraction.",
    paragraphs: [
      site.intro,
      "Lately that has extended to applied AI: using models as components inside real systems rather than as demos, with the same attention to failure modes, cost, and latency.",
    ],
    link: { label: "→ DOWNLOAD RESUME", href: site.resume },
    psTag: "P.S.",
    ps: "Most of this gets built late at night, with filter coffee and a Counter-Strike round between deploys.",
  },

  /** Reads the `skills` groups directly — no second copy of the list. */
  stack: {
    label: "STACK",
  },

  currently: {
    label: "CURRENTLY",
    cells: [
      { key: "BUILDING", value: "PropVexis — real-time trading infrastructure" },
      { key: "LEARNING", value: "Applied AI engineering" },
      { key: "EXPLORING", value: "Cloud architecture and distributed systems" },
      { key: "OUTSIDE WORK", value: "Counter-Strike · Coffee · Building things" },
    ],
  },

  ask: {
    label: "04 / ASK",
    system: "KNOWLEDGE SYSTEM",
    online: "ONLINE",
    title: ["ASK ME", "ANYTHING."],
    blurb:
      "Instead of searching through my portfolio, ask my AI assistant about my experience, projects, technologies, or what I'm currently building.",
    formLabel: "ASK ABOUT MY EXPERIENCE, PROJECTS, OR WHAT I'M BUILDING",
    placeholder: "Type a question…",
    palettePlaceholder: "Ask about experience, projects, technologies…",
    schematic: ["QUESTION", "CONTEXT", "RETRIEVAL", "RESPONSE"],
    kbLabel: "KNOWLEDGE BASE",
    kbActive: "ACTIVE",
    kbRows: { projects: "PROJECTS", experience: "EXPERIENCE", tech: "TECHNOLOGIES", focus: "CURRENT FOCUS" },
    statusIdle: "ASSISTANT STATUS",
    statusOpen: "ASSISTANT",
    stateReady: "READY",
    stateBusy: "RETRIEVING",
    queryLabel: "QUERY",
    responseLabel: "RESPONSE",
    retrievingLabel: "RETRIEVING CONTEXT…",
    /** Occupies the design's SOURCE slot, and has to stay true. */
    sourceLabel: "SOURCE",
    source: "FIXED KNOWLEDGE BASE · GEMINI",
    sourceFailed: "—",
    suggestionsLabel: "SUGGESTED QUERIES",
    relatedLabel: "RELATED QUERIES",
    relatedHref: { label: "Browse selected work", href: "#work" },
    reset: "← NEW QUERY",
    esc: "ESC",
    enterToAsk: "TO ASK",
  },

  contact: {
    title: ["LET'S BUILD", "SOMETHING", "INTERESTING."],
    /** Rendered as icons in the send row; `value` is the accessible name. */
    links: [
      { id: "email", label: "Email", value: site.email, href: `mailto:${site.email}` },
      { id: "linkedin", label: "LinkedIn", value: "/in/anish358", href: site.linkedin },
      { id: "github", label: "GitHub", value: "@Anish358", href: site.github },
    ],
    fields: {
      name: { label: "NAME", placeholder: "Your name" },
      email: { label: "EMAIL", placeholder: "your@email.com" },
      message: {
        label: "MESSAGE",
        placeholder: "Tell me a little about what you're working on.",
      },
    },
    required: "REQUIRED",
    invalidEmail: "ENTER A VALID EMAIL",
    sending: "SENDING…",
    submit: "SEND MESSAGE →",
    sent: {
      label: "MESSAGE SENT",
      text: "Thank you — I'll get back to you soon.",
      note: "TRANSMITTED SUCCESSFULLY",
    },
    failed: {
      label: "UNABLE TO SEND",
      text: "Something went wrong. Please try again.",
      retry: "RETRY →",
    },
  },

  notFound: {
    chapter: "ERROR 404",
    eyebrow: "PAGE NOT FOUND",
    title: ["THIS PAGE", "DOESN'T EXIST."],
    lede: "The address is wrong, or whatever used to be here has moved.",
    links: [
      { label: "→ HOME", href: "/" },
      { label: "→ SELECTED WORK", href: "/#work" },
      { label: "→ CONTACT", href: "/#contact" },
    ],
    status: "NO ROUTE MATCHED",
  },

  footer: {
    left: `${site.name.toUpperCase()} — ${year}`,
    right: "Built with curiosity.",
  },
} as const;

/** Row counts for the ASK panel's knowledge-base table. Derived, never typed. */
export const knowledgeBase = {
  projects: projects.length,
  experience: experience.length,
  technologies: skills.reduce((total, group) => total + group.items.length, 0),
} as const;

/**
 * Chrome for the editorial case-study template.
 *
 * Layout and every measurement come from
 * editorial-design-system-new/project/"PropVexis - Case Study.dc.html".
 * The substance — problem, features, decisions, next steps, diagram, pipeline
 * — is read from the exports above, so this holds only the page furniture.
 *
 * `/luxora` was never mocked. It's the same template with the sections it has
 * content for, which is exactly how the design brief framed it.
 */
export const caseStudyPages = {
  propvexis: {
    chrome: "CASE STUDY 01 / SELECTED WORK",
    eyebrow: "FLAGSHIP / LIVE IN PRODUCTION",
    title: "PROPVEXIS",
    subject: "RISK MANAGEMENT FOR FUNDED TRADERS",
    period: "2025 —",
    lede: "Real-time drawdown tracking that tells a trader where they stand right now, not what happened yesterday.",
    aside: [
      { label: "STATUS", kind: "status", value: "LIVE IN PRODUCTION" },
      {
        label: "LIVE SITE",
        kind: "link",
        value: "app.propvexis.com",
        href: "https://app.propvexis.com",
      },
      {
        label: "GITHUB",
        kind: "link",
        value: "github.com/Anish358/propvexis",
        href: "https://github.com/Anish358/propvexis",
      },
      { label: "STACK", kind: "stack" },
    ],
    problem: { label: "01 / THE PROBLEM", counter: "01 — 06", tag: "ONE SHOT" },
    dataPath: {
      label: "02 / HOW IT FITS TOGETHER",
      counter: "DATA PATH",
      figure: "FIG. 01 — CLOSED TRADE FROM TERMINAL TO SCREEN",
      mode: "WRITE PATH / IDEMPOTENT",
    },
    features: { label: "03 / WHAT IT DOES", counter: "04 FEATURES" },
    tradeOffs: {
      label: "04 / TRADE-OFFS",
      counter: "06 DECISIONS",
      headline: "WHAT I CHOSE, AND WHAT IT COST.",
      blurb:
        "Six decisions where the alternative was reasonable and I picked the other one. Each of these is a constraint the system now lives with.",
    },
    pipeline: { label: "05 / PIPELINE", counter: "05 STAGES / GITHUB ACTIONS" },
    infrastructure: {
      label: "06 / INFRASTRUCTURE",
      counter: "03 ENVIRONMENTS",
      runtimeLabel: "RUNTIME",
      runtime: [
        { key: "HOST", value: "AWS EC2" },
        { key: "ENVIRONMENTS", value: "03" },
        { key: "SECRETS", value: "SSM" },
        { key: "OBSERVABILITY", value: "GRAFANA · SENTRY" },
        { key: "BACKUPS", value: "NIGHTLY / S3", accent: true },
      ],
    },
    whatsNext: { label: "07 / WHAT'S NEXT", counter: "03 ITEMS" },
    nextProject: {
      kicker: "NEXT PROJECT — 02",
      name: "LUXORA",
      href: "/luxora",
    },
    palette: {
      placeholder: "Ask about this project, the stack, the trade-offs…",
      suggestions: [
        "What does PropVexis actually do?",
        "How does a trade reach the browser?",
        "What was the hardest trade-off?",
        "How is it deployed?",
      ],
    },
  },

  luxora: {
    chrome: "CASE STUDY 02 / SELECTED WORK",
    eyebrow: "E-COMMERCE PLATFORM",
    title: "LUXORA",
    subject: "CATALOGUE, CART AND FULFILMENT",
    /** No dated period on record for this one, so the rule row runs unbroken. */
    period: null,
    lede: "A storefront, a customer account and an operator console — three apps over one Express API.",
    aside: [
      { label: "STATUS", kind: "status", value: "LIVE" },
      {
        label: "LIVE SITE",
        kind: "link",
        value: "luxora-mu.vercel.app",
        href: "https://luxora-mu.vercel.app/",
      },
      {
        label: "GITHUB",
        kind: "link",
        value: "github.com/Anish358/luxora",
        href: "https://github.com/Anish358/luxora",
      },
      { label: "STACK", kind: "stack" },
    ],
    problem: { label: "01 / THE PROBLEM", counter: "01 — 02", tag: "THE FIDDLY PARTS" },
    dataPath: null,
    features: { label: "02 / WHAT IT DOES", counter: "03 FEATURES" },
    tradeOffs: null,
    pipeline: null,
    infrastructure: null,
    whatsNext: null,
    nextProject: {
      kicker: "NEXT PROJECT — 01",
      name: "PROPVEXIS",
      href: "/propvexis",
    },
    palette: {
      placeholder: "Ask about this project, the stack, the trade-offs…",
      suggestions: [
        "What is Luxora?",
        "What did he build into it?",
        "How does its admin panel work?",
        "What technologies does Anish work with?",
      ],
    },
  },
} as const;

/** Shared furniture across both case studies. */
export const caseStudyChrome = {
  back: "← ANISH SHEJAWALE",
  nav: [
    { label: "WORK", href: "/#work" },
    { label: "CONTACT", href: "/#contact" },
  ],
  end: "END OF CASE STUDY",
  allProjects: { label: "← ALL PROJECTS", href: "/#work" },
  viewProject: "VIEW PROJECT →",
} as const;
